server:
  port: 8888
spring:
  application:
    name: mssc-brewery-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springframeworkguru/mssc-example-config-repo
          clone-on-start: true
logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug
