server:
  port: 8888
spring:
  application:
    name: mssc-brewery-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adetiamarhadi/mssc-brewery-config-repo.git
          clone-on-start: true
          searchPaths: '{application}'
logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug
